(define (make-from-mag-ang r a)
  (define (dispath op)
    (cond ((eq? op 'magnitude) r)
          ((eq? op 'angle) a)
          ((eq? op 'real-part)
           (* r (cos a)))
          ((eq? op 'imag-part)
           (* r (sin a)))
          (else
            (error "Unknown op -- MAKE-FROM-MAG-ANG" op))))
  dispath)
